### ISSUE TITLE
V2 format (was: Metadata section removed from Cargo.lock)

### ISSUE THREAD

**Issue by Jake-Shadle** [RustSec/cargo-lock#26]
This change in cargo https://github.com/rust-lang/cargo/pull/7070 removed the `[metadata]` section from `Cargo.lock`, and 1.38 is the first cargo version that supports the new format. The current nightly has changed the new format to be the default, so at some point in the future the metadata section will disappear from stable.

**Comment by tarcieri** [comment]
I think what you're asking for is better support for the V2 format? We'll always need to support the metadata section in order to support the V1 format...

**Comment by Jake-Shadle** [comment]
Oh no, sorry, not asking for anything specifically, I just had an [issue](https://github.com/EmbarkStudios/cargo-deny/issues/56) on one of my repos and as I was using this crate (via rustsec) I just wanted to post an issue in case you weren't aware.

**Comment by tarcieri** [comment]
Aah, ok then. I have been meaning to do an overhaul to add proper V2 format support, including having an enum of versions and "remembering" the version which was parsed so that version is used when serializing, as well as ensuring the parsed fields are consistent between both versions.
