### ISSUE TITLE
Detect root packages in cargo lock tree

### ISSUE THREAD

**Issue by jplatte** [RustSec/cargo-lock#64]
I found [this TODO comment](https://github.com/RustSec/cargo-lock/blob/6c7e9fa612e89e797b85a77327f67a1732bb5d2c/src/bin/cargo-lock/main.rs#L123) when looking for how to use the `dependency-tree` feature, and thought I'd share my solution for that:

```rust
// TODO: pass through flags like --manifest-path
let metadata = MetadataCommand::new().no_deps().exec()?;

let dependencies: Vec<_> =
        metadata.workspace_members.iter().map(|pkg_id| &metadata[pkg_id]).collect();

// the same loop that's already in your code base, slightly updated
for (i, dep) in dependencies.iter().enumerate() {
    if i > 0 {
        println!();
    }

    let package = lockfile
        .packages
        .iter()
        .find(|pkg| {
            // you were matching only on package name before, this should be more robust
            pkg.name.as_str() == dep.name
                && pkg.version == dep.version
                && pkg.source.as_ref().map(|s| s.to_string()).as_ref()
                    == dep.source.as_ref().map(|s| &s.repr)
        })
        .with_context(|| {
            format!(
                "Couldn't find `{} {}{}` in lockfile.",
                dep.name.as_str(),
                dep.version,
                match &dep.source {
                    Some(s) => format!(" ({})", s),
                    None => String::new(),
                }
            )
        })?;

    let index = tree.nodes()[&package.into()];
    tree.render(&mut io::stdout(), index, EdgeDirection::Incoming).unwrap();
}
```

Thanks a lot for creating this project, it is really useful!

**Comment by tarcieri** [comment]
Neat, thanks! As it were I was just poking around at this project today thinking about some new features like that. Thanks for the solution.

**Comment by jplatte** [comment]
You might want to coordinate a shared `Source` / `SourceId` type with the cargo_metadata folks for even easier package comparison between `Cargo.lock` and the `cargo metadata` output :)

**Comment by tarcieri** [comment]
It'd be amazing if there were some sort of meta crate for crates like `cargo_metadata` and `cargo-lock` to use to share types. I can open an issue about it on the `cargo_metadata` tracker.

**Comment by tarcieri** [comment]
Looking at this, it appears to need `cargo_metadata` as a dependency. I was hoping for a more self-contained solution.

I think it should be possible to compute by looking for entries in the graph that have no incoming edges.

**Comment by jplatte** [comment]
That will only give you a small subset of workspace crates. They can and very often do depend on each other.

If you don't want to depend on `cargo_metadata` for this, you can just reimplement the relevant parts of it, the only thing it does is call `cargo metadata` and parse its output.

**Comment by tarcieri** [comment]
It doesn't really matter where the crates come from, be it crates.io or the workspace. The point is to find the "root" crates in the DAG.

**Comment by jplatte** [comment]
Oh, I see. For some reason I thought that the TODO comment was referring to workspace members rather than tree roots. If you just want the packages without incoming edges, petgraph [has a function for that](https://docs.rs/petgraph/0.5.1/petgraph/graph/struct.Graph.html#method.externals).

**Comment by tarcieri** [comment]
Nice, thanks
