### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by UebelAndre** [RustSec/cargo-lock#68]
would it be possible to get a new release of this package?

**Comment by tarcieri** [comment]
Yes, I plan on cutting another release soon.

That said, is there something in particular you want? There haven't been any significant changes since the last release...

**Comment by UebelAndre** [comment]
I specifically want the updated `semver` dependency. This would unblock the pull request to `cargo raze` linked to this issue.

**Comment by tarcieri** [comment]
I've just released 5.0.0-rc: https://crates.io/crates/cargo-lock/5.0.0-rc

Please let me know if it looks good, and if so, I can cut a final release.

**Comment by UebelAndre** [comment]
@tarcieri LGTM!

**Comment by tarcieri** [comment]
Cool, waiting for review from one other person. Will hopefully cut a final release later today.

**Comment by tarcieri** [comment]
Looking like tomorrow for a release, but hopefully the `-rc` suffices for now.

**Comment by UebelAndre** [comment]
It does, thank you! You can close this issue if you want or wait for the release.

Thanks again! 😄

**Comment by tarcieri** [comment]
v5.0.0 has been released (#82)
